export enum ActionId {
  REFRESH = 'REFRESH',
  CREATE_TEAM = 'CREATE_TEAM',
  DELETE_TEAM = 'DELETE_TEAM',
  UPDATE_TEAM = 'UPDATE_TEAM',
  ADD_MEMBERS_TO_TEAM = 'ADD_MEMBERS_TO_TEAM',
  REMOVE_MEMBERS_FROM_TEAM = 'REMOVE_MEMBERS_FROM_TEAM',
  RESET_USER_BUG_COUNT = 'RESET_USER_BUG_COUNT',
  REMOVE_USER_FROM_APP = 'REMOVE_USER_FROM_APP'
}
